[package]
name = "aboidant"
version = "0.1.0"
authors = ["iancormac84 <wilnathan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/iancormac84/bevy.git", branch = "pbr-on-main" }
bevy_flycam = { git = "https://github.com/iancormac84/bevy_flycam.git", branch = "pbr-update" }
